[versions]
activity = "1.12.1"
annotation = "1.9.1"
app-compat = "1.7.1"
agp = "8.13.1"
androidx-junit = "1.3.0"
ktx = "1.17.0"
ksp = "2.3.3"
kotlin = "2.2.21"
constraint-layout-version = "2.2.1"
android-test-core = "1.7.0"
android-test-rules = "1.7.0"
android-test-runner = "1.7.0"
android-sqlite = "2.6.2"
core-testing = "2.2.0"
kotlinx-coroutines = "1.10.2"
kotlin-test = "2.0.0"
leakcanary-android = "2.14"
robolectric = "4.16"
mockk = "1.14.7"
room = "2.8.4"
retrofit = "3.0.0"
koin = "4.1.1"
coroutines = "1.10.2"
lifecycle-ktx = "2.10.0"
recycler-view = "1.4.0"
card-view = "1.0.0"
swipe-refresh-layout = "1.2.0"
glide = "5.0.5"
moshi = "1.15.2"
okhttp = "5.3.2"
junit = "4.13.2"
material = "1.13.0"
dependency-analysis = "3.5.1"
jetbrainsKotlinJvm = "2.2.21"

[libraries]
android-gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
androidx-activity = { module = "androidx.activity:activity", version.ref = "activity" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
androidx-lifecycle-common = { module = "androidx.lifecycle:lifecycle-common", version.ref = "lifecycle-ktx" }
androidx-lifecycle-livedata-core = { module = "androidx.lifecycle:lifecycle-livedata-core", version.ref = "lifecycle-ktx" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycle-ktx" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle-ktx" }
androidx-sqlite = { module = "androidx.sqlite:sqlite", version.ref = "android-sqlite" }
androidx-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "ktx" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraint-layout-version" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
app-compat = { group = "androidx.appcompat", name = "appcompat", version.ref = "app-compat" }
leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary-android" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-common = { module = "androidx.room:room-common", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
square-retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
square-retrofit-converter-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
kotlinx-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
recycler-view = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recycler-view" }
bumptech-glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
bumptech-glide-compiler = { group = "com.github.bumptech.glide", name = "ksp", version.ref = "glide" }
card-view = { group = "androidx.cardview", name = "cardview", version.ref = "card-view" }
square-moshi-codegen = { group = "com.squareup.moshi", name = "moshi-kotlin-codegen", version.ref = "moshi" }
square-moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
square-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
swipe-refresh-layout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swipe-refresh-layout" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

# test libraries

kotlin-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin-test" }
android-test-runner = { group = "androidx.test", name = "runner", version.ref = "android-test-runner" }
android-test-rules = { group = "androidx.test", name = "rules", version.ref = "android-test-rules" }
android-test-core = { group = "androidx.test", name = "core", version.ref = "android-test-core" }
android-core-testing = { group = "androidx.arch.core", name = "core-testing", version.ref = "core-testing" }
android-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-junit" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
mockk-dsl = { module = "io.mockk:mockk-dsl", version.ref = "mockk" }
junit = { module = "junit:junit", version.ref = "junit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp-plugin = { id = "com.google.devtools.ksp", version.ref = "ksp" }
dependency-analysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependency-analysis" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
android-library = { id = "com.android.library", version.ref = "agp" }
